version: "3"
services:

  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
        - 7474:7474
        - 7687:7687
    volumes: 
        - neo4j-data:/data
        - neo4j-logs:/logs
        - neo4j-conf:/conf
    environment:
        # neo4j password setting (NEO4J_AUTH=neo4j/<password>)
        - NEO4J_AUTH=neo4j/neo4jj

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-conf:
  redis-data: